@echo OFF
cls
echo.   PROG01          PROG02          PROG03
echo.   PROG04          PROG05          PROG06
echo.   PROG07          PROG08          PROG09
echo.   PROG10          PROG11          INFO
echo.
echo.   CLASE01         CLASE02         CLASE03
echo.   CLASE04         CLASE05         CLASE06
echo.   CLASE07         CLASE08         EXAMEN
echo.
echo. Para visualizar un programa debe de escribir el nombre del
echo. programa (p.ej. PROG04) 
echo.
echo. Si lo que desea es ver una peque¤a descripcion
echo. de que hace cada uno de los programas
echo. debera teclear INFO y presionar enter


