#include<stdio.h>
#include<conio.h>
#include<d:\c4v4\lib.h>
#include<math.h>

main (void)
      {
	  double   a,b,x,ftol,xtol;
	  int   n,ntol;
	  clrscr;
	  printf ("METODO DE BUSQUEDA DE RAICES DE ECUACIONES NO LINEALES");
	  printf ("\n\n********************* BISECCION **********************");
	  Inicializar_adquisicion;
	  while (!= final)
	     elemento_siguiente;
	     resultados;
//	  repeat until keypressed;

     }

